"""require document owner

Revision ID: 96cbce9a33f8
Revises: 583b193a4a72
Create Date: 2026-09-23 09:23:35.548634

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "96cbce9a33f8"
down_revision: str | Sequence[str] | None = "583b193a4a72"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("documents", "user_id", existing_type=sa.VARCHAR(length=36), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("documents", "user_id", existing_type=sa.VARCHAR(length=36), nullable=True)
    # ### end Alembic commands ###
